// mail2im/frontend/src/views/Dashboard.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import api from '../services/api';
import PageHeader from '../components/PageHeader.vue';
import Button from 'primevue/button';
import Tag from 'primevue/tag';

const { t } = useI18n();

const stats = ref({
  emails: 0,
  accounts: 0,
  proxies: 0,
  channels: 0
});

const loading = ref(false);
const refreshing = ref(false);
const recentLogs = ref<any[]>([]);

const loadData = async () => {
  loading.value = true;
  try {
    const [emailsRes, accountsRes, proxiesRes, channelsRes, logsRes] = await Promise.all([
      api.get('/emails', { params: { page: 1, pageSize: 1 } }),
      api.get('/accounts'),
      api.get('/proxies'),
      api.get('/channels'),
      api.get('/logs')
    ]);

    stats.value = {
      emails: emailsRes.data.total || emailsRes.data?.data?.length || 0,
      accounts: accountsRes.data?.length || 0,
      proxies: proxiesRes.data?.length || 0,
      channels: channelsRes.data?.length || 0
    };

    recentLogs.value = (logsRes.data || []).slice(0, 5);
  } catch (error) {
    console.error(error);
  } finally {
    loading.value = false;
    refreshing.value = false;
  }
};

const refresh = async () => {
  refreshing.value = true;
  await loadData();
};

onMounted(loadData);
</script>

<template>
  <div class="page">
    <PageHeader :title="t('dashboard.title')">
      <template #actions>
        <Button icon="pi pi-refresh" :aria-label="t('common.refresh')" text rounded :loading="refreshing" @click="refresh" v-tooltip.bottom="t('common.refresh')" />
      </template>
    </PageHeader>

    <div class="page-panel">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
        <div class="stat-card">
          <div class="label">{{ t('dashboard.emails') }}</div>
          <div class="value">{{ stats.emails }}</div>
        </div>
        <div class="stat-card">
          <div class="label">{{ t('dashboard.accounts') }}</div>
          <div class="value">{{ stats.accounts }}</div>
        </div>
        <div class="stat-card">
          <div class="label">{{ t('dashboard.proxies') }}</div>
          <div class="value">{{ stats.proxies }}</div>
        </div>
        <div class="stat-card">
          <div class="label">{{ t('dashboard.channels') }}</div>
          <div class="value">{{ stats.channels }}</div>
        </div>
      </div>

      <div class="flex flex-col gap-4 flex-1 min-h-0">
        <div class="section-header">
          <h3>{{ t('dashboard.recent_logs') }}</h3>
        </div>
        <div class="dashboard-logs-container">
          <div v-if="loading" class="text-sm text-surface-500">{{ t('dashboard.loading') }}</div>
          <div v-else-if="recentLogs.length === 0" class="text-sm text-surface-500">{{ t('dashboard.no_logs') }}</div>
          <div v-else class="dashboard-logs-content">
            <div v-for="(log, index) in recentLogs" :key="index" class="log-row">
              <div class="log-meta">
                <Tag :value="log.status" severity="info" />
                <span class="time">{{ new Date(log.received_at).toLocaleString() }}</span>
              </div>
              <div class="log-content">
                <div class="subject">{{ log.subject || '-' }}</div>
                <div class="from text-sm text-surface-500">{{ log.from }}</div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.stat-card {
  background: var(--p-surface-0);
  border: 1px solid var(--p-surface-200);
  border-radius: 10px;
  padding: 1rem 1.25rem;
  display: flex;
  flex-direction: column;
  gap: 0.35rem;
  box-shadow: 0 1px 4px rgba(0, 0, 0, 0.04);
}

.app-dark .stat-card {
  background: var(--p-surface-900);
  border-color: var(--p-surface-800);
}

.stat-card .label {
  color: var(--p-text-muted-color);
  font-size: 0.95rem;
}

.stat-card .value {
  font-weight: 700;
  font-size: 1.5rem;
}

.section-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
}

.section-header h3 {
  margin: 0;
}

.log-row {
  border: 1px solid var(--p-surface-200);
  border-radius: 10px;
  padding: 0.75rem 1rem;
}

.app-dark .log-row {
  border-color: var(--p-surface-800);
}

.log-meta {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}

.log-meta .time {
  color: var(--p-text-muted-color);
  font-size: 0.85rem;
}

.log-content .subject {
  font-weight: 600;
  margin-bottom: 0.25rem;
}

/* Dashboard logs container for scroll */
.dashboard-logs-container {
  flex: 1;
  min-height: 0;
  overflow: auto;
}

.dashboard-logs-content {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}
</style>

// mail2im/frontend-react/src/pages/Dashboard.tsx
import { useQueries } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { format } from 'date-fns'
import { RefreshCw, Mail, Users, Globe, Bell } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { PageHeader } from '@/components/PageHeader'
import api, { extractList } from '@/services/api'

interface LogEntry {
  id?: number
  ID?: number
  status: string
  priority: number
  action?: string
  channel_name?: string
  channel?: string
  channel_id?: number
  from?: string
  subject?: string
  received_at?: string
  forwarded_at?: string
  error?: string
  request?: string
  response?: string
  message_id?: string
}

interface EmailsResponse {
  total?: number
  data?: unknown[]
}

function StatCard({
  label,
  value,
  icon: Icon,
}: {
  label: string
  value: number | string
  icon: React.ElementType
}) {
  return (
    <div className="rounded-xl border bg-card p-5 flex items-start gap-4 shadow-xs">
      <div className="h-10 w-10 rounded-lg bg-primary/8 flex items-center justify-center shrink-0">
        <Icon className="h-5 w-5 text-primary" />
      </div>
      <div className="flex flex-col gap-0.5 min-w-0">
        <span className="text-sm text-muted-foreground">{label}</span>
        <span className="text-2xl font-semibold tabular-nums">{value}</span>
      </div>
    </div>
  )
}

function getStatusVariant(status: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (status) {
    case 'success':
      return 'default'
    case 'failed':
      return 'destructive'
    case 'received':
      return 'secondary'
    default:
      return 'outline'
  }
}

export function DashboardPage() {
  const { t } = useTranslation()

  const results = useQueries({
    queries: [
      {
        queryKey: ['emails-count'],
        queryFn: async () => {
          const res = await api.get<EmailsResponse | unknown[]>('/emails', { params: { page: 1, pageSize: 1 } })
          const data = res.data as EmailsResponse & unknown[]
          return (data as EmailsResponse).total ?? (Array.isArray(data) ? data.length : 0)
        },
      },
      {
        queryKey: ['dashboard', 'accounts-count'],
        queryFn: async () => {
          const res = await api.get<unknown[]>('/accounts')
          return Array.isArray(res.data) ? res.data.length : 0
        },
      },
      {
        queryKey: ['dashboard', 'proxies-count'],
        queryFn: async () => {
          const res = await api.get<unknown[]>('/proxies')
          return Array.isArray(res.data) ? res.data.length : 0
        },
      },
      {
        queryKey: ['dashboard', 'channels-count'],
        queryFn: async () => {
          const res = await api.get<unknown[]>('/channels')
          return Array.isArray(res.data) ? res.data.length : 0
        },
      },
      {
        queryKey: ['logs-recent'],
        queryFn: async () => {
          const res = await api.get<LogEntry[]>('/logs')
          return extractList(res.data).slice(0, 5)
        },
      },
    ],
  })

  const [emailsQ, accountsQ, proxiesQ, channelsQ, logsQ] = results

  const isLoading = results.some((r) => r.isLoading)

  const refetchAll = () => {
    results.forEach((r) => r.refetch())
  }

  const stats = [
    { label: t('dashboard.emails'), value: emailsQ.data ?? '-', icon: Mail },
    { label: t('dashboard.accounts'), value: accountsQ.data ?? '-', icon: Users },
    { label: t('dashboard.proxies'), value: proxiesQ.data ?? '-', icon: Globe },
    { label: t('dashboard.channels'), value: channelsQ.data ?? '-', icon: Bell },
  ]

  const recentLogs = (logsQ.data ?? []) as LogEntry[]

  return (
    <div className="flex flex-col h-full">
      <PageHeader
        title={t('dashboard.title')}
        className="px-4 md:px-6 py-4 border-b"
        actions={
          <Button
            variant="ghost"
            size="icon"
            onClick={refetchAll}
            disabled={isLoading}
            aria-label={t('common.refresh')}
          >
            <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
          </Button>
        }
      />

      <div className="flex-1 overflow-auto px-4 md:px-6 py-6">
        {/* Stats */}
        <div className="grid grid-cols-2 md:grid-cols-4 gap-3 md:gap-4 mb-6">
          {stats.map((s) => (
            <StatCard key={s.label} label={s.label} value={s.value} icon={s.icon} />
          ))}
        </div>

        {/* Recent Logs */}
        <div className="flex flex-col gap-3">
          <h2 className="text-sm font-medium text-muted-foreground uppercase tracking-wider">
            {t('dashboard.recent_logs')}
          </h2>

          {logsQ.isLoading ? (
            <p className="text-sm text-muted-foreground">{t('dashboard.loading')}</p>
          ) : recentLogs.length === 0 ? (
            <p className="text-sm text-muted-foreground">{t('dashboard.no_logs')}</p>
          ) : (
            <div className="flex flex-col gap-2">
              {recentLogs.map((log, i) => {
                const dateStr = log.received_at ?? log.forwarded_at
                return (
                  <div
                    key={log.id ?? log.ID ?? i}
                    className="rounded-xl border bg-card px-4 py-3 flex flex-col gap-1"
                  >
                    <div className="flex items-center gap-2">
                      <Badge variant={getStatusVariant(log.status)}>{log.status}</Badge>
                      {dateStr && (
                        <span className="text-xs text-muted-foreground">
                          {format(new Date(dateStr), 'yyyy-MM-dd HH:mm:ss')}
                        </span>
                      )}
                    </div>
                    <p className="text-sm font-medium truncate">{log.subject || '-'}</p>
                    <p className="text-xs text-muted-foreground truncate">{log.from || ''}</p>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
