// mail2im/frontend/src/views/EmailStandalone.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import api from '../services/api';
import { useAuthStore } from '../stores/auth';
import Toast from 'primevue/toast';

const route = useRoute();
const router = useRouter();
const { t } = useI18n();
const toast = useToast();
const auth = useAuthStore();
const appName = 'Mail2IM';

const email = ref<any>(null);
const loading = ref(false);
const htmlSrc = ref('');
const srcDoc = ref('');

const buildHtmlSrc = async (id: string) => {
  await auth.ensureSession();
  const token = auth.accessToken;
  const tokenQuery = token ? `?access_token=${encodeURIComponent(token)}` : '';
  htmlSrc.value = `/api/emails/${id}/html${tokenQuery}`;
};

const setTitle = (text: string) => {
  document.title = text ? `${text} - ${appName}` : appName;
};

const fetchEmail = async () => {
  loading.value = true;
  const id = (route.params.id as string) || '';
  const token = (route.params.token as string) || '';

  if (!id && !token) {
    loading.value = false;
    return;
  }

  try {
    if (token) {
        // Public access
        const res = await api.get(`/public/emails/${token}`);
        email.value = res.data;
        srcDoc.value = email.value.html_body || email.value.text_body || '';
        // If no HTML, wrap text
        if (!email.value.html_body && email.value.text_body) {
            srcDoc.value = `<pre style="white-space: pre-wrap; font-family: sans-serif;">${email.value.text_body}</pre>`;
        }
    } else {
        // Private access
        const res = await api.get(`/emails/${id}`);
        email.value = res.data;
        await buildHtmlSrc(id);
    }
    setTitle(email.value?.subject || t('common.email_detail'));
  } catch (error) {
    console.error(error);
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('emails_view.load_error'), life: 3000 });
  } finally {
    loading.value = false;
  }
};

const backToList = () => {
  if (route.params.token) return; // No back button for public view
  const url = router.resolve({ name: 'emails' }).href;
  window.open(url, '_blank');
};

const formatDate = (dateStr: string) => {
  if (!dateStr) return '-';
  const d = new Date(dateStr);
  return isNaN(d.getTime()) ? '-' : d.toLocaleString();
};

onMounted(fetchEmail);
</script>

<template>
  <div class="standalone">
    <Toast position="top-center" />
    <div class="viewer">
      <div class="viewer-header">
        <div class="title-block">
          <div class="subject">{{ email?.subject || '-' }}</div>
          <div class="meta">
            <span>{{ t('emails_view.mailbox') }}: {{ email?.mailbox || email?.mailbox_path || '-' }}</span>
            <span>·</span>
            <span>{{ t('common.from') }}: {{ email?.from || '-' }}</span>
            <span>·</span>
            <span>{{ t('common.to') }}: {{ email?.to || '-' }}</span>
            <span>·</span>
            <span>{{ t('common.received_at') }}: {{ formatDate(email?.received_at) }}</span>
          </div>
        </div>
        <div class="actions">
          <Button icon="pi pi-refresh" :label="t('common.refresh')" text rounded @click="fetchEmail" :loading="loading" />
          <Button icon="pi pi-ellipsis-v" text rounded :aria-label="t('emails_view.more_actions')" />
          <Button icon="pi pi-list" :label="t('emails_view.list')" text rounded @click="backToList" />
        </div>
      </div>

      <div class="iframe-wrapper">
        <iframe
          v-if="!loading"
          :src="srcDoc ? undefined : htmlSrc"
          :srcdoc="srcDoc || undefined"
          class="mail-frame"
          sandbox="allow-same-origin allow-popups"
          referrerpolicy="no-referrer"
        ></iframe>
        <div v-else class="loading">
          <i class="pi pi-spin pi-spinner text-3xl"></i>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.standalone {
  min-height: 100vh;
  background: #f8fafc;
  padding: 0;
  box-sizing: border-box;
  display: flex;
}

.viewer {
  width: 100%;
  min-height: 100vh;
  background: white;
  display: flex;
  flex-direction: column;
  gap: 1rem;
  padding: 1rem 1.25rem;
}

.viewer-header {
  display: flex;
  align-items: center;
  justify-content: space-between;
  flex-wrap: wrap;
  gap: 1rem;
}

.title-block {
  display: flex;
  flex-direction: column;
  gap: 0.25rem;
}

.subject {
  font-size: 1.25rem;
  font-weight: var(--fw-heading);
  color: #0f172a;
}

.meta {
  display: flex;
  gap: 0.5rem;
  color: #64748b;
  font-size: 0.95rem;
  flex-wrap: wrap;
}

.actions {
  display: flex;
  gap: 0.5rem;
}

.iframe-wrapper {
  border: 1px solid #e2e8f0;
  border-radius: 12px;
  overflow: hidden;
  flex: 1;
  min-height: 60vh;
  background: #f8fafc;
}

.mail-frame {
  width: 100%;
  height: 100%;
  border: none;
  background: white;
}

.loading {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
}

@media (max-width: 768px) {
  .viewer {
    padding: 1rem;
  }

  .actions {
    width: 100%;
    justify-content: flex-start;
    flex-wrap: wrap;
  }
}
</style>

// mail2im/frontend-react/src/pages/EmailStandalone.tsx
import { useEffect, useState } from 'react'
import { useParams } from 'react-router'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import { RefreshCw, X } from 'lucide-react'
import api from '@/services/api'
import { useAuthStore } from '@/stores/auth'
import { Button } from '@/components/ui/button'

const APP_NAME = 'Mail2IM'

type EmailData = {
  id?: number
  subject?: string
  from?: string
  to?: string
  mailbox?: string
  mailbox_path?: string
  received_at?: string
  html_body?: string
  text_body?: string
}

function formatDate(dateStr: string) {
  if (!dateStr) return '-'
  const d = new Date(dateStr)
  return isNaN(d.getTime()) ? '-' : d.toLocaleString()
}

function StandaloneHeader({
  email,
  loading,
  onRefresh,
  onClose,
  showClose,
}: {
  email: EmailData | null
  loading: boolean
  onRefresh: () => void
  onClose?: () => void
  showClose: boolean
}) {
  const { t } = useTranslation()
  return (
    <div className="flex items-center justify-between gap-4 flex-wrap px-5 py-3 border-b bg-background">
      <div className="flex flex-col gap-0.5 min-w-0">
        <h1 className="text-lg font-semibold text-foreground truncate">
          {email?.subject || '-'}
        </h1>
        <div className="flex gap-2 text-sm text-muted-foreground flex-wrap">
          {email?.mailbox && (
            <span>{t('emails_view.mailbox')}: {email.mailbox || email.mailbox_path || '-'}</span>
          )}
          {email?.from && (
            <>
              <span>·</span>
              <span>{t('common.from')}: {email.from}</span>
            </>
          )}
          {email?.to && (
            <>
              <span>·</span>
              <span>{t('common.to')}: {email.to}</span>
            </>
          )}
          {email?.received_at && (
            <>
              <span>·</span>
              <span>{t('common.received_at')}: {formatDate(email.received_at)}</span>
            </>
          )}
        </div>
      </div>
      <div className="flex items-center gap-2 shrink-0">
        <Button
          variant="ghost"
          size="sm"
          onClick={onRefresh}
          disabled={loading}
          title={t('common.refresh')}
        >
          <RefreshCw className={`h-4 w-4 ${loading ? 'animate-spin' : ''}`} />
        </Button>
        {showClose && (
          <Button
            variant="ghost"
            size="sm"
            onClick={onClose}
            title={t('common.close')}
          >
            <X className="h-4 w-4" />
          </Button>
        )}
      </div>
    </div>
  )
}

export function EmailStandalonePage() {
  const { t } = useTranslation()
  const { id } = useParams<{ id: string }>()
  const accessToken = useAuthStore((s) => s.accessToken)

  const [email, setEmail] = useState<EmailData | null>(null)
  const [loading, setLoading] = useState(false)
  const [htmlSrc, setHtmlSrc] = useState('')

  const fetchEmail = async () => {
    if (!id) return
    setLoading(true)
    try {
      const res = await api.get(`/emails/${id}`)
      setEmail(res.data as EmailData)
    } catch {
      toast.error(t('emails_view.load_error'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchEmail()
  }, [id])

  useEffect(() => {
    if (!id) return
    const tokenQuery = accessToken ? `?access_token=${encodeURIComponent(accessToken)}` : ''
    setHtmlSrc(`/api/emails/${id}/html${tokenQuery}`)
  }, [id, accessToken])

  useEffect(() => {
    document.title = email?.subject ? `${email.subject} - ${APP_NAME}` : APP_NAME
    return () => { document.title = APP_NAME }
  }, [email?.subject])

  const handleClose = () => window.close()

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <StandaloneHeader
        email={email}
        loading={loading}
        onRefresh={fetchEmail}
        onClose={handleClose}
        showClose
      />
      <div className="flex-1 border-t overflow-hidden" style={{ minHeight: '0' }}>
        {loading ? (
          <div className="flex items-center justify-center h-full min-h-[60vh] text-muted-foreground">
            <RefreshCw className="h-6 w-6 animate-spin" />
          </div>
        ) : htmlSrc ? (
          <iframe
            src={htmlSrc}
            className="w-full border-none bg-white"
            style={{ height: 'calc(100vh - 80px)' }}
            sandbox="allow-same-origin allow-popups"
            referrerPolicy="no-referrer"
            title={email?.subject || 'Email'}
          />
        ) : (
          <div className="flex items-center justify-center h-full min-h-[60vh] text-muted-foreground text-sm">
            {t('emails_view.load_error')}
          </div>
        )}
      </div>
    </div>
  )
}

export function SharePage() {
  const { t } = useTranslation()
  const { token } = useParams<{ token: string }>()

  const [email, setEmail] = useState<EmailData | null>(null)
  const [loading, setLoading] = useState(false)
  const [srcDoc, setSrcDoc] = useState('')

  const fetchEmail = async () => {
    if (!token) return
    setLoading(true)
    try {
      const res = await api.get(`/public/emails/${token}`)
      const data = res.data as EmailData
      setEmail(data)
      if (data.html_body) {
        setSrcDoc(data.html_body)
      } else if (data.text_body) {
        setSrcDoc(`<pre style="white-space: pre-wrap; font-family: sans-serif;">${data.text_body}</pre>`)
      } else {
        setSrcDoc('')
      }
    } catch {
      toast.error(t('emails_view.load_error'))
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchEmail()
  }, [token])

  useEffect(() => {
    document.title = email?.subject ? `${email.subject} - ${APP_NAME}` : APP_NAME
    return () => { document.title = APP_NAME }
  }, [email?.subject])

  return (
    <div className="flex flex-col min-h-screen bg-background">
      <StandaloneHeader
        email={email}
        loading={loading}
        onRefresh={fetchEmail}
        showClose={false}
      />
      <div className="flex-1 overflow-hidden">
        {loading ? (
          <div className="flex items-center justify-center h-full min-h-[60vh] text-muted-foreground">
            <RefreshCw className="h-6 w-6 animate-spin" />
          </div>
        ) : srcDoc ? (
          <iframe
            srcDoc={srcDoc}
            className="w-full border-none bg-white"
            style={{ height: 'calc(100vh - 80px)' }}
            sandbox="allow-same-origin allow-popups"
            referrerPolicy="no-referrer"
            title={email?.subject || 'Email'}
          />
        ) : (
          <div className="flex items-center justify-center h-full min-h-[60vh] text-muted-foreground text-sm">
            {t('emails_view.load_error')}
          </div>
        )}
      </div>
    </div>
  )
}
