// mail2im/frontend/src/views/Logs.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import api from '../services/api';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Tag from 'primevue/tag';
import Button from 'primevue/button';
import Dialog from 'primevue/dialog';
import { format } from 'date-fns';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import PageHeader from '../components/PageHeader.vue';
import { getNumber, setString, KEYS } from '../utils/storage';

const { t } = useI18n();
const toast = useToast();

const logs = ref([]);
const loading = ref(false);
const detailVisible = ref(false);
const detailLog = ref<any>(null);
const deleteLogDialog = ref(false);
const deleteTarget = ref<any>(null);
const deleteLoading = ref(false);
const clearLogsDialog = ref(false);
const clearLoading = ref(false);
const rowsOptions = [10, 20, 50];
const logRows = ref(getNumber(KEYS.TABLE_ROWS_LOGS, 10));
const logFirst = ref(0);

const fetchLogs = async () => {
  loading.value = true;
  try {
    const res = await api.get('/logs');
    logs.value = res.data;
  } catch (e) {
    console.error(e);
  } finally {
    loading.value = false;
  }
};

const getSeverity = (status: string) => {
  switch (status) {
    case 'success': return 'success';
    case 'failed': return 'danger';
    case 'received': return 'info';
    default: return 'info';
  }
};

const formatDate = (dateStr: string) => {
  return format(new Date(dateStr), 'yyyy-MM-dd HH:mm:ss');
};

const getPrioritySeverity = (priority: number) => {
  if (priority >= 3) return 'danger';
  if (priority === 2) return 'warning';
  if (priority === 1) return 'info';
  return 'secondary';
};

const getPriorityLabel = (priority: number) => {
  switch (priority) {
    case 3: return t('channels.priority_critical');
    case 2: return t('channels.priority_high');
    case 1: return t('channels.priority_normal');
    default: return t('channels.priority_low');
  }
};

const showDetail = (row: any) => {
  detailLog.value = row;
  detailVisible.value = true;
};

const confirmDeleteLog = (row: any) => {
  deleteTarget.value = row;
  deleteLogDialog.value = true;
};

const deleteLog = async () => {
  if (!deleteTarget.value) return;
  deleteLoading.value = true;
  try {
    const id = deleteTarget.value.id || deleteTarget.value.ID;
    await api.delete(`/logs/${id}`);
    toast.add({ severity: 'success', summary: t('common.success'), detail: t('logs.delete_success'), life: 2500 });
    deleteLogDialog.value = false;
    await fetchLogs();
  } catch (e) {
    console.error(e);
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('logs.delete_error'), life: 2500 });
  } finally {
    deleteLoading.value = false;
  }
};

const confirmClearLogs = () => {
  clearLogsDialog.value = true;
};

const clearLogs = async () => {
  clearLoading.value = true;
  try {
    await api.delete('/logs');
    toast.add({ severity: 'success', summary: t('common.success'), detail: t('logs.clear_success'), life: 2500 });
    clearLogsDialog.value = false;
    await fetchLogs();
  } catch (e) {
    console.error(e);
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('logs.clear_error'), life: 2500 });
  } finally {
    clearLoading.value = false;
  }
};

const onPage = (event: any) => {
  logRows.value = event.rows;
  logFirst.value = event.first;
  setString(KEYS.TABLE_ROWS_LOGS, String(event.rows));
};

onMounted(fetchLogs);

const tablePt = {
  mask: { style: { background: 'transparent', boxShadow: 'none', opacity: 1, pointerEvents: 'none' } },
  loadingOverlay: { style: { background: 'transparent', boxShadow: 'none' } }
};
</script>

<template>
  <div class="page table-page">
    <PageHeader :title="t('logs.title')">
      <template #actions>
        <Button icon="pi pi-trash" severity="danger" text rounded @click="confirmClearLogs" :aria-label="t('logs.clear')" v-tooltip.bottom="t('logs.clear')" />
        <Button icon="pi pi-refresh" @click="fetchLogs" :loading="loading" rounded text :aria-label="t('common.refresh')" v-tooltip.bottom="t('common.refresh')" />
      </template>
    </PageHeader>

    <div class="page-panel table-panel">
      <div class="table-wrapper">
        <DataTable
          :value="logs"
          paginator
          :rows="logRows"
          :first="logFirst"
          :loading="loading"
          stripedRows
          tableStyle="min-width: 60rem"
          scrollable
          scrollHeight="flex"
          class="table-fill"
          :pt="tablePt"
          :rowsPerPageOptions="rowsOptions"
          paginatorTemplate="FirstPageLink PrevPageLink PageLinks NextPageLink LastPageLink CurrentPageReport RowsPerPageDropdown"
          currentPageReportTemplate="{first} to {last} of {totalRecords}"
          @page="onPage"
        >
          <Column field="priority" :header="t('logs.priority')" style="width: 8rem">
            <template #body="slotProps">
              <Tag :value="getPriorityLabel(slotProps.data.priority)" :severity="getPrioritySeverity(slotProps.data.priority)" />
            </template>
          </Column>
          <Column field="status" :header="t('logs.status')">
            <template #body="slotProps">
              <Tag :value="slotProps.data.status" :severity="getSeverity(slotProps.data.status)" />
            </template>
          </Column>
          <Column field="action" :header="t('logs.action')">
            <template #body="slotProps">
              {{ slotProps.data.action || '-' }}
            </template>
          </Column>
          <Column :header="t('logs.channel')">
            <template #body="slotProps">
              <div class="flex flex-column gap-1">
                <span class="font-medium">{{ slotProps.data.channel_name || slotProps.data.channel || '-' }}</span>
                <small v-if="slotProps.data.channel_id" class="text-color-secondary">#{{ slotProps.data.channel_id }}</small>
              </div>
            </template>
          </Column>
          <Column field="received_at" :header="t('logs.time')">
            <template #body="slotProps">
              {{ formatDate(slotProps.data.received_at || slotProps.data.forwarded_at) }}
            </template>
          </Column>
          <Column field="from" :header="t('logs.from')"></Column>
          <Column field="subject" :header="t('logs.subject')"></Column>
          <Column field="error" :header="t('logs.error')">
            <template #body="slotProps">
              <span v-if="slotProps.data.error" class="text-red-400">{{ slotProps.data.error }}</span>
              <span v-else>-</span>
            </template>
          </Column>
          <Column :header="t('logs.details')" style="width: 10rem" :exportable="false">
            <template #body="slotProps">
              <Button icon="pi pi-search" text rounded class="mr-2" @click="showDetail(slotProps.data)" :aria-label="t('logs.details')" />
              <Button icon="pi pi-trash" text rounded severity="danger" @click="confirmDeleteLog(slotProps.data)" :aria-label="t('logs.delete')" />
            </template>
          </Column>
        </DataTable>
      </div>
    </div>

    <Dialog v-model:visible="detailVisible" modal :header="t('logs.details')" :style="{ width: '40rem' }">
      <div v-if="detailLog" class="log-detail">
        <div class="detail-row">
          <span class="label">{{ t('logs.action') }}</span>
          <span>{{ detailLog.action || '-' }}</span>
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.status') }}</span>
          <Tag :value="detailLog.status" :severity="getSeverity(detailLog.status)" />
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.priority') }}</span>
          <Tag :value="getPriorityLabel(detailLog.priority)" :severity="getPrioritySeverity(detailLog.priority)" />
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.channel') }}</span>
          <span>{{ detailLog.channel_name || detailLog.channel || '-' }} <span v-if="detailLog.channel_id" class="text-color-secondary">(#{{ detailLog.channel_id }})</span></span>
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.from') }}</span>
          <span>{{ detailLog.from || '-' }}</span>
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.subject') }}</span>
          <span>{{ detailLog.subject || '-' }}</span>
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.message_id') }}</span>
          <span>{{ detailLog.message_id || '-' }}</span>
        </div>
        <div class="detail-row">
          <span class="label">{{ t('logs.time') }}</span>
          <span>{{ formatDate(detailLog.received_at || detailLog.forwarded_at) }}</span>
        </div>
        <div class="detail-block" v-if="detailLog.request">
          <div class="block-title">{{ t('logs.request') }}</div>
          <pre>{{ detailLog.request }}</pre>
        </div>
        <div class="detail-block" v-if="detailLog.response">
          <div class="block-title">{{ t('logs.response') }}</div>
          <pre>{{ detailLog.response }}</pre>
        </div>
        <div class="detail-block" v-if="detailLog.error">
          <div class="block-title text-red-500">{{ t('logs.error') }}</div>
          <pre class="text-red-500">{{ detailLog.error }}</pre>
        </div>
      </div>
    </Dialog>

    <Dialog v-model:visible="deleteLogDialog" modal :header="t('common.confirm')" :style="{ width: '26rem' }">
      <p class="mb-4">{{ t('logs.delete_confirm') }}</p>
      <div class="flex justify-end gap-2">
        <Button :label="t('common.no')" icon="pi pi-times" text @click="deleteLogDialog = false" />
        <Button :label="t('common.yes')" icon="pi pi-check" :loading="deleteLoading" severity="danger" @click="deleteLog" />
      </div>
    </Dialog>

    <Dialog v-model:visible="clearLogsDialog" modal :header="t('common.confirm')" :style="{ width: '28rem' }">
      <p class="mb-4">{{ t('logs.clear_confirm') }}</p>
      <div class="flex justify-end gap-2">
        <Button :label="t('common.no')" icon="pi pi-times" text @click="clearLogsDialog = false" />
        <Button :label="t('common.yes')" icon="pi pi-check" :loading="clearLoading" severity="danger" @click="clearLogs" />
      </div>
    </Dialog>
  </div>
</template>

<style scoped>
.log-detail {
  display: flex;
  flex-direction: column;
  gap: 0.5rem;
}

.detail-row {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-size: 0.95rem;
}

.detail-row .label {
  min-width: 7rem;
  color: var(--text-color-secondary, #6b7280);
  font-weight: 600;
}

.detail-block {
  margin-top: 0.25rem;
  padding: 0.75rem;
  background: #f8fafc;
  border: 1px solid #e5e7eb;
  border-radius: 8px;
}

.block-title {
  font-weight: 600;
  margin-bottom: 0.25rem;
}

pre {
  white-space: pre-wrap;
  word-break: break-all;
  margin: 0;
  font-family: Menlo, Monaco, Consolas, 'Courier New', monospace;
}
</style>

// mail2im/frontend-react/src/pages/Logs.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import {
  useReactTable,
  getCoreRowModel,
  getPaginationRowModel,
  flexRender,
  type ColumnDef,
} from '@tanstack/react-table'
import { format } from 'date-fns'
import { RefreshCw, Trash2, Eye, ChevronLeft, ChevronRight } from 'lucide-react'
import { toast } from 'sonner'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { PageHeader } from '@/components/PageHeader'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import api, { extractList } from '@/services/api'

interface LogEntry {
  id?: number
  ID?: number
  status: string
  priority: number
  action?: string
  channel_name?: string
  channel?: string
  channel_id?: number
  from?: string
  subject?: string
  received_at?: string
  forwarded_at?: string
  error?: string
  request?: string
  response?: string
  message_id?: string
}

function getStatusVariant(status: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (status) {
    case 'success':
      return 'default'
    case 'failed':
      return 'destructive'
    case 'received':
      return 'secondary'
    default:
      return 'outline'
  }
}

function getPriorityVariant(priority: number): 'default' | 'secondary' | 'destructive' | 'outline' {
  if (priority >= 3) return 'destructive'
  if (priority === 2) return 'default'
  if (priority === 1) return 'secondary'
  return 'outline'
}

function getPriorityLabel(priority: number, t: (key: string) => string): string {
  switch (priority) {
    case 3: return t('common.priority_critical')
    case 2: return t('common.priority_high')
    case 1: return t('common.priority_normal')
    default: return t('common.priority_low')
  }
}

function formatDate(dateStr?: string): string {
  if (!dateStr) return '-'
  try {
    return format(new Date(dateStr), 'yyyy-MM-dd HH:mm:ss')
  } catch {
    return dateStr
  }
}

function getLogId(log: LogEntry): number | undefined {
  return log.id ?? log.ID
}

// Detail Dialog
function LogDetailDialog({
  log,
  open,
  onOpenChange,
}: {
  log: LogEntry | null
  open: boolean
  onOpenChange: (open: boolean) => void
}) {
  const { t } = useTranslation()
  if (!log) return null

  const rows: { label: string; content: React.ReactNode }[] = [
    { label: t('logs.action'), content: log.action || '-' },
    {
      label: t('logs.status'),
      content: <Badge variant={getStatusVariant(log.status)}>{log.status}</Badge>,
    },
    {
      label: t('logs.priority'),
      content: (
        <Badge variant={getPriorityVariant(log.priority)}>
          {getPriorityLabel(log.priority, t)}
        </Badge>
      ),
    },
    {
      label: t('logs.channel'),
      content: (
        <span>
          {log.channel_name || log.channel || '-'}
          {log.channel_id ? (
            <span className="ml-1 text-muted-foreground text-xs">(#{log.channel_id})</span>
          ) : null}
        </span>
      ),
    },
    { label: t('logs.from'), content: log.from || '-' },
    { label: t('logs.subject'), content: log.subject || '-' },
    { label: t('logs.message_id'), content: log.message_id || '-' },
    {
      label: t('logs.time'),
      content: formatDate(log.received_at ?? log.forwarded_at),
    },
  ]

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="max-w-xl">
        <DialogHeader>
          <DialogTitle>{t('logs.details')}</DialogTitle>
        </DialogHeader>
        <div className="flex flex-col gap-3 text-sm">
          {rows.map((row) => (
            <div key={row.label} className="flex items-start gap-3">
              <span className="min-w-24 text-muted-foreground font-medium shrink-0">
                {row.label}
              </span>
              <span className="break-all">{row.content}</span>
            </div>
          ))}
          {log.request && (
            <div className="flex flex-col gap-1">
              <span className="text-muted-foreground font-medium">{t('logs.request')}</span>
              <pre className="bg-muted rounded-lg p-3 text-xs whitespace-pre-wrap break-all font-mono overflow-auto max-h-40">
                {log.request}
              </pre>
            </div>
          )}
          {log.response && (
            <div className="flex flex-col gap-1">
              <span className="text-muted-foreground font-medium">{t('logs.response')}</span>
              <pre className="bg-muted rounded-lg p-3 text-xs whitespace-pre-wrap break-all font-mono overflow-auto max-h-40">
                {log.response}
              </pre>
            </div>
          )}
          {log.error && (
            <div className="flex flex-col gap-1">
              <span className="text-destructive font-medium">{t('logs.error')}</span>
              <pre className="bg-destructive/10 text-destructive rounded-lg p-3 text-xs whitespace-pre-wrap break-all font-mono overflow-auto max-h-40">
                {log.error}
              </pre>
            </div>
          )}
        </div>
      </DialogContent>
    </Dialog>
  )
}

export function LogsPage() {
  const { t } = useTranslation()
  const queryClient = useQueryClient()

  const [detailLog, setDetailLog] = useState<LogEntry | null>(null)
  const [deleteTarget, setDeleteTarget] = useState<LogEntry | null>(null)
  const [showClearDialog, setShowClearDialog] = useState(false)

  const { data: logs = [], isLoading, refetch } = useQuery<LogEntry[]>({
    queryKey: ['logs'],
    queryFn: async () => {
      const res = await api.get<LogEntry[]>('/logs')
      return extractList(res.data)
    },
  })

  const deleteMutation = useMutation({
    mutationFn: async (log: LogEntry) => {
      const id = getLogId(log)
      await api.delete(`/logs/${id}`)
    },
    onSuccess: () => {
      toast.success(t('logs.delete_success'))
      setDeleteTarget(null)
      queryClient.invalidateQueries({ queryKey: ['logs'] })
      queryClient.invalidateQueries({ queryKey: ['logs-recent'] })
    },
    onError: () => {
      toast.error(t('logs.delete_error'))
    },
  })

  const clearMutation = useMutation({
    mutationFn: async () => {
      await api.delete('/logs')
    },
    onSuccess: () => {
      toast.success(t('logs.clear_success'))
      setShowClearDialog(false)
      queryClient.invalidateQueries({ queryKey: ['logs'] })
      queryClient.invalidateQueries({ queryKey: ['logs-recent'] })
    },
    onError: () => {
      toast.error(t('logs.clear_error'))
    },
  })

  const columns: ColumnDef<LogEntry>[] = [
    {
      accessorKey: 'status',
      header: t('logs.status'),
      cell: ({ row }) => (
        <Badge variant={getStatusVariant(row.original.status)}>
          {row.original.status}
        </Badge>
      ),
    },
    {
      accessorKey: 'priority',
      header: t('logs.priority'),
      cell: ({ row }) => (
        <Badge variant={getPriorityVariant(row.original.priority)}>
          {getPriorityLabel(row.original.priority, t)}
        </Badge>
      ),
    },
    {
      id: 'channel',
      header: t('logs.channel'),
      cell: ({ row }) => (
        <span>{row.original.channel_name || row.original.channel || '-'}</span>
      ),
    },
    {
      accessorKey: 'from',
      header: t('logs.from'),
      cell: ({ row }) => (
        <span className="max-w-40 truncate block">{row.original.from || '-'}</span>
      ),
    },
    {
      accessorKey: 'subject',
      header: t('logs.subject'),
      cell: ({ row }) => (
        <span className="max-w-48 truncate block">{row.original.subject || '-'}</span>
      ),
    },
    {
      id: 'time',
      header: t('logs.time'),
      cell: ({ row }) => (
        <span className="text-xs text-muted-foreground whitespace-nowrap">
          {formatDate(row.original.received_at ?? row.original.forwarded_at)}
        </span>
      ),
    },
    {
      id: 'actions',
      header: '',
      cell: ({ row }) => (
        <div className="flex items-center gap-1 justify-end">
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7"
            onClick={() => setDetailLog(row.original)}
            aria-label={t('logs.details')}
          >
            <Eye className="h-3.5 w-3.5" />
          </Button>
          <Button
            variant="ghost"
            size="icon"
            className="h-7 w-7 text-destructive hover:text-destructive"
            onClick={() => setDeleteTarget(row.original)}
            aria-label={t('logs.delete')}
          >
            <Trash2 className="h-3.5 w-3.5" />
          </Button>
        </div>
      ),
    },
  ]

  const table = useReactTable({
    data: logs,
    columns,
    getCoreRowModel: getCoreRowModel(),
    getPaginationRowModel: getPaginationRowModel(),
    initialState: { pagination: { pageSize: 20 } },
  })

  const { pageIndex, pageSize } = table.getState().pagination
  const totalRows = logs.length
  const from = totalRows === 0 ? 0 : pageIndex * pageSize + 1
  const to = Math.min((pageIndex + 1) * pageSize, totalRows)

  return (
    <div className="flex flex-col gap-4 h-full">
      <PageHeader
        title={t('logs.title')}
        actions={
          <>
            <Button
              variant="ghost"
              size="icon"
              onClick={() => refetch()}
              disabled={isLoading}
              aria-label={t('common.refresh')}
            >
              <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
            </Button>
            <Button
              variant="ghost"
              size="icon"
              className="text-destructive hover:text-destructive"
              onClick={() => setShowClearDialog(true)}
              aria-label={t('logs.clear')}
            >
              <Trash2 className="h-4 w-4" />
            </Button>
          </>
        }
      />

      {/* Table */}
      <div className="flex flex-col flex-1 min-h-0">
        <div className="overflow-auto flex-1">
          <Table>
            <TableHeader>
              {table.getHeaderGroups().map((hg) => (
                <TableRow key={hg.id}>
                  {hg.headers.map((header) => (
                    <TableHead key={header.id}>
                      {header.isPlaceholder
                        ? null
                        : flexRender(header.column.columnDef.header, header.getContext())}
                    </TableHead>
                  ))}
                </TableRow>
              ))}
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={columns.length} className="text-center py-10 text-muted-foreground text-sm">
                    {t('dashboard.loading')}
                  </TableCell>
                </TableRow>
              ) : table.getRowModel().rows.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={columns.length} className="text-center py-10 text-muted-foreground text-sm">
                    {t('dashboard.no_logs')}
                  </TableCell>
                </TableRow>
              ) : (
                table.getRowModel().rows.map((row) => (
                  <TableRow
                    key={row.id}
                    className="cursor-pointer"
                    onClick={() => setDetailLog(row.original)}
                  >
                    {row.getVisibleCells().map((cell) => (
                      <TableCell
                        key={cell.id}
                        onClick={
                          cell.column.id === 'actions'
                            ? (e) => e.stopPropagation()
                            : undefined
                        }
                      >
                        {flexRender(cell.column.columnDef.cell, cell.getContext())}
                      </TableCell>
                    ))}
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>

        {/* Pagination */}
        <div className="flex items-center justify-between px-4 py-3 border-t text-sm text-muted-foreground">
          <span>
            {totalRows === 0
              ? '0'
              : `${from}–${to} / ${totalRows}`}
          </span>
          <div className="flex items-center gap-1">
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={() => table.previousPage()}
              disabled={!table.getCanPreviousPage()}
            >
              <ChevronLeft className="h-4 w-4" />
            </Button>
            <span className="px-2 text-xs">
              {pageIndex + 1} / {table.getPageCount() || 1}
            </span>
            <Button
              variant="ghost"
              size="icon"
              className="h-7 w-7"
              onClick={() => table.nextPage()}
              disabled={!table.getCanNextPage()}
            >
              <ChevronRight className="h-4 w-4" />
            </Button>
          </div>
        </div>
      </div>

      {/* Detail Dialog */}
      <LogDetailDialog
        log={detailLog}
        open={detailLog !== null}
        onOpenChange={(open) => { if (!open) setDetailLog(null) }}
      />

      {/* Delete single log */}
      <AlertDialog open={deleteTarget !== null} onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('common.confirm')}</AlertDialogTitle>
            <AlertDialogDescription>{t('logs.delete_confirm')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('common.no')}</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-white hover:bg-destructive/90"
              onClick={() => deleteTarget && deleteMutation.mutate(deleteTarget)}
              disabled={deleteMutation.isPending}
            >
              {t('common.yes')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>

      {/* Clear all logs */}
      <AlertDialog open={showClearDialog} onOpenChange={setShowClearDialog}>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogTitle>{t('common.confirm')}</AlertDialogTitle>
            <AlertDialogDescription>{t('logs.clear_confirm')}</AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('common.no')}</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-white hover:bg-destructive/90"
              onClick={() => clearMutation.mutate()}
              disabled={clearMutation.isPending}
            >
              {t('common.yes')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}
