// mail2im/frontend-react/src/pages/EmailDetail.tsx
import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router'
import { useTranslation } from 'react-i18next'
import { useQuery } from '@tanstack/react-query'
import { toast } from 'sonner'
import { ArrowLeft, ExternalLink, RefreshCw } from 'lucide-react'
import api from '@/services/api'
import { useAuthStore } from '@/stores/auth'
import { Button } from '@/components/ui/button'
import { Separator } from '@/components/ui/separator'

type EmailDetail = {
  id: number
  subject: string
  from: string
  to: string
  mailbox: string
  mailbox_path?: string
  mail_type: string
  received_at: string
  is_read: boolean
}

function formatDate(dateStr: string) {
  if (!dateStr) return '-'
  const d = new Date(dateStr)
  return isNaN(d.getTime()) ? '-' : d.toLocaleString()
}

function MetaItem({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex gap-2 items-baseline min-w-0">
      <span className="text-muted-foreground text-sm shrink-0">{label}</span>
      <span className="text-sm text-foreground truncate" title={value}>
        {value || '-'}
      </span>
    </div>
  )
}

export function EmailDetailPage() {
  const { t } = useTranslation()
  const { id } = useParams<{ id: string }>()
  const navigate = useNavigate()
  const accessToken = useAuthStore((s) => s.accessToken)

  const [htmlSrc, setHtmlSrc] = useState('')

  const {
    data: email,
    isLoading,
    isError,
    refetch,
  } = useQuery<EmailDetail>({
    queryKey: ['email', id],
    queryFn: async () => {
      const res = await api.get(`/emails/${id}`)
      return res.data as EmailDetail
    },
    enabled: !!id,
    retry: false,
  })

  useEffect(() => {
    if (!isError) return
    toast.error(t('emails_view.load_error'))
  }, [isError, t])

  useEffect(() => {
    if (!id) return
    const tokenQuery = accessToken ? `?access_token=${encodeURIComponent(accessToken)}` : ''
    setHtmlSrc(`/api/emails/${id}/html${tokenQuery}`)
  }, [id, accessToken])

  useEffect(() => {
    if (email?.subject) {
      document.title = `${email.subject} - Mail2IM`
    } else {
      document.title = 'Mail2IM'
    }
    return () => {
      document.title = 'Mail2IM'
    }
  }, [email?.subject])

  const goBack = () => {
    if (window.history.length > 1) {
      navigate(-1)
    } else {
      navigate('/emails')
    }
  }

  const openStandalone = () => {
    if (!id) return
    const tokenQuery = accessToken ? `?access_token=${encodeURIComponent(accessToken)}` : ''
    window.open(`/api/emails/${id}/html${tokenQuery}`, '_blank')
  }

  return (
    <div className="flex flex-col h-full gap-4 p-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3">
          <Button variant="ghost" size="sm" onClick={goBack} className="gap-1.5">
            <ArrowLeft className="h-4 w-4" />
            {t('common.back')}
          </Button>
          <Separator orientation="vertical" className="h-5" />
          <h1 className="text-lg font-semibold tracking-tight truncate max-w-md">
            {isLoading ? t('common.email_detail') : (email?.subject || t('common.email_detail'))}
          </h1>
        </div>
        <div className="flex items-center gap-2">
          <Button
            variant="ghost"
            size="sm"
            onClick={() => refetch()}
            disabled={isLoading}
            title={t('common.refresh')}
          >
            <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
          </Button>
          <Button variant="outline" size="sm" onClick={openStandalone} className="gap-1.5">
            <ExternalLink className="h-4 w-4" />
            {t('common.view')}
          </Button>
        </div>
      </div>

      {isLoading ? (
        <div className="flex-1 flex items-center justify-center text-muted-foreground">
          <div className="flex flex-col items-center gap-3">
            <RefreshCw className="h-6 w-6 animate-spin" />
            <span className="text-sm">{t('dashboard.loading')}</span>
          </div>
        </div>
      ) : isError ? (
        <div className="flex-1 flex items-center justify-center text-muted-foreground text-sm">
          {t('emails_view.load_error')}
        </div>
      ) : email ? (
        <div className="flex flex-col flex-1 min-h-0 gap-4">
          {/* Metadata card */}
          <div className="rounded-lg border border-border bg-card px-5 py-4 space-y-2.5">
            <h2 className="text-xl font-semibold leading-tight">{email.subject || '-'}</h2>
            <Separator />
            <div className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-1.5">
              <MetaItem label={t('common.from')} value={email.from} />
              <MetaItem label={t('common.to')} value={email.to} />
              <MetaItem
                label={t('emails_view.mailbox')}
                value={email.mailbox || email.mailbox_path || '-'}
              />
              <MetaItem label={t('common.received_at')} value={formatDate(email.received_at)} />
            </div>
          </div>

          {/* iframe email content */}
          <div className="flex-1 min-h-0 rounded-lg border border-border overflow-hidden bg-white">
            {htmlSrc ? (
              <iframe
                src={htmlSrc}
                className="w-full h-full border-none"
                style={{ minHeight: '60vh' }}
                sandbox="allow-same-origin allow-popups"
                referrerPolicy="no-referrer"
                title={email.subject || 'Email'}
              />
            ) : (
              <div className="flex items-center justify-center h-full text-muted-foreground text-sm">
                {t('emails_view.load_error')}
              </div>
            )}
          </div>
        </div>
      ) : null}
    </div>
  )
}

// mail2im/frontend/src/views/EmailDetail.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import api from '../services/api';
import { useAuthStore } from '../stores/auth';
import PageHeader from '../components/PageHeader.vue';

const route = useRoute();
const router = useRouter();
const { t } = useI18n();
const toast = useToast();
const auth = useAuthStore();

const email = ref<any>(null);
const loading = ref(false);
const htmlSrc = ref('');
const appName = 'Mail2IM';

const buildHtmlSrc = async (id: string) => {
    await auth.ensureSession();
    const token = auth.accessToken;
    const tokenQuery = token ? `?access_token=${encodeURIComponent(token)}` : '';
    htmlSrc.value = `/api/emails/${id}/html${tokenQuery}`;
};

const setTitle = (text: string) => {
    document.title = text ? `${text} - ${appName}` : appName;
};

const fetchEmail = async () => {
    loading.value = true;
    const id = (route.params.id as string) || '';
    if (!id) {
        loading.value = false;
        return;
    }
    try {
        const res = await api.get(`/emails/${id}`);
        email.value = res.data;
        const titleText = email.value?.subject || t('common.email_detail');
        setTitle(titleText);
        await buildHtmlSrc(id);
    } catch (error) {
        console.error(error);
        toast.add({ severity: 'error', summary: t('common.error'), detail: t('emails_view.load_error'), life: 3000 });
    } finally {
        loading.value = false;
    }
};

const refreshEmail = () => fetchEmail();

const openStandalone = () => {
    const id = email.value?.id || route.params.id;
    if (!id) return;
    const url = router.resolve({ name: 'email-standalone', params: { id } }).href;
    window.open(url, '_blank');
};

const goBack = () => {
    if (window.history.length > 1) {
        router.back();
    } else {
        router.push('/emails');
    }
};

const formatDate = (dateStr: string) => {
    if (!dateStr) return '';
    return new Date(dateStr).toLocaleString();
};

onMounted(() => {
    fetchEmail();
});
</script>

<template>
    <div class="page detail-page">
        <PageHeader :title="t('common.email_detail')" :show-back="true" @back="goBack">
            <template #actions>
                <Button icon="pi pi-refresh" text rounded :loading="loading" @click="refreshEmail" :aria-label="t('common.refresh')" />
                <Button icon="pi pi-ellipsis-v" text rounded :aria-label="t('emails_view.more_actions')" />
                <Button icon="pi pi-external-link" rounded @click="openStandalone" :label="t('common.view')" />
            </template>
        </PageHeader>

        <div class="page-panel detail-panel">
            <div v-if="loading" class="flex justify-center p-8">
                <i class="pi pi-spin pi-spinner text-4xl"></i>
            </div>

            <div v-else-if="email" class="viewer">
                <div class="viewer-header">
                    <div class="title-block">
                        <div class="subject">{{ email.subject || '-' }}</div>
                        <div class="meta">
                            <span>{{ t('emails_view.mailbox') }}: {{ email.mailbox || email.mailbox_path || '-' }}</span>
                            <span>·</span>
                            <span>{{ t('common.from') }}: {{ email.from || '-' }}</span>
                            <span>·</span>
                            <span>{{ t('common.to') }}: {{ email.to || '-' }}</span>
                            <span>·</span>
                            <span>{{ t('common.received_at') }}: {{ formatDate(email.received_at) }}</span>
                        </div>
                    </div>
                </div>

                <div class="iframe-wrapper">
                    <iframe
                        v-if="!loading"
                        :src="htmlSrc"
                        class="mail-frame"
                        sandbox="allow-same-origin allow-popups"
                        referrerpolicy="no-referrer"
                    ></iframe>
                    <div v-else class="loading">
                        <i class="pi pi-spin pi-spinner text-3xl"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<style scoped>
.detail-page {
    height: 100%;
    display: flex;
    flex-direction: column;
    gap: 1rem;
}

.detail-panel {
    flex: 1;
    display: flex;
    flex-direction: column;
    min-height: 0;
}

.viewer {
    display: flex;
    flex-direction: column;
    gap: 1rem;
    flex: 1;
    min-height: 0;
}

.viewer-header {
    display: flex;
    align-items: center;
    justify-content: space-between;
    flex-wrap: wrap;
    gap: 1rem;
}

.title-block {
    display: flex;
    flex-direction: column;
    gap: 0.25rem;
}

.subject {
    font-size: 1.25rem;
    font-weight: var(--fw-heading);
}

.meta {
    display: flex;
    gap: 0.5rem;
    color: var(--p-text-muted-color, #64748b);
    font-size: 0.95rem;
    flex-wrap: wrap;
}

.actions {
    display: flex;
    gap: 0.5rem;
}

.iframe-wrapper {
    border: 1px solid var(--p-surface-200);
    border-radius: 12px;
    overflow: hidden;
    flex: 1;
    min-height: 70vh;
    background: var(--p-surface-50);
}

.mail-frame {
    width: 100%;
    height: 100%;
    border: none;
    background: white;
}

.loading {
    display: flex;
    align-items: center;
    justify-content: center;
    height: 100%;
}

@media (max-width: 768px) {
    .actions {
        width: 100%;
        justify-content: flex-start;
        flex-wrap: wrap;
    }
}
</style>
