// mail2im/frontend-react/src/pages/NotificationPolicy.tsx
import { useState } from 'react'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { useTranslation } from 'react-i18next'
import { toast } from 'sonner'
import {
  RefreshCw,
  Inbox,
  Wallet,
  Star,
  Bell,
  HelpCircle,
  Megaphone,
  Users,
  Ban,
  Trash2,
  FileEdit,
  Send,
  Tag,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Checkbox } from '@/components/ui/checkbox'
import { Badge } from '@/components/ui/badge'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import api, { extractList } from '@/services/api'
import { PageHeader } from '@/components/PageHeader'

// ─── Types ───────────────────────────────────────────────────────────────────

interface PolicyChannel {
  id: number
  name: string
  type: string
  selected: boolean
}

interface PolicyItem {
  ID: number
  key: string
  name: string
  priority: number
  is_system: boolean
  action: string
  channel_ids: string
  channels: PolicyChannel[]
}

// ─── Icon map ─────────────────────────────────────────────────────────────────

const TYPE_ICONS: Record<string, React.ElementType> = {
  primary: Inbox,
  bill: Wallet,
  important: Star,
  notification: Bell,
  unknown: HelpCircle,
  promotion: Megaphone,
  social: Users,
  spam: Ban,
  trash: Trash2,
  draft: FileEdit,
  sent: Send,
}

function TypeIcon({ mailKey }: { mailKey: string }) {
  const Icon = TYPE_ICONS[mailKey] ?? Tag
  return <Icon className="h-4 w-4 shrink-0 text-muted-foreground" />
}

// ─── Page ─────────────────────────────────────────────────────────────────────

export function NotificationPolicyPage() {
  const { t } = useTranslation()
  const queryClient = useQueryClient()
  const [saving, setSaving] = useState<string | null>(null)

  // Fetch policy list (channels embedded per item)
  const { data: items = [], isFetching } = useQuery<PolicyItem[]>({
    queryKey: ['notification-policy'],
    queryFn: async () => {
      const res = await api.get<PolicyItem[]>('/notification-policy')
      return extractList(res.data)
    },
  })

  // Single-item update mutation
  const updateMutation = useMutation({
    mutationFn: async ({ key, payload }: { key: string; payload: { channel_ids: string; action: string; priority: number } }) => {
      await api.put(`/notification-policy/${key}`, payload)
    },
    onSuccess: (_data, { key }) => {
      toast.success(t('policy.update_success'))
      setSaving(null)
      queryClient.invalidateQueries({ queryKey: ['notification-policy'] })
      // optimistic: key used to track spinner
      void key
    },
    onError: () => {
      toast.error(t('policy.update_error'))
      setSaving(null)
    },
  })

  const updateItem = (item: PolicyItem) => {
    setSaving(item.key)
    const selectedIds = item.channels.filter((c) => c.selected).map((c) => c.id)
    updateMutation.mutate({
      key: item.key,
      payload: {
        channel_ids: JSON.stringify(selectedIds),
        action: item.action,
        priority: item.priority,
      },
    })
  }

  const handleToggleChannel = (item: PolicyItem, channelId: number) => {
    // Mutate local query cache optimistically
    queryClient.setQueryData<PolicyItem[]>(['notification-policy'], (old) =>
      (old ?? []).map((it) =>
        it.key === item.key
          ? {
              ...it,
              channels: it.channels.map((ch) =>
                ch.id === channelId ? { ...ch, selected: !ch.selected } : ch
              ),
            }
          : it
      )
    )
    // Build updated item for server call
    const updatedItem: PolicyItem = {
      ...item,
      channels: item.channels.map((ch) =>
        ch.id === channelId ? { ...ch, selected: !ch.selected } : ch
      ),
    }
    updateItem(updatedItem)
  }

  const handleActionChange = (item: PolicyItem, newAction: string) => {
    queryClient.setQueryData<PolicyItem[]>(['notification-policy'], (old) =>
      (old ?? []).map((it) => (it.key === item.key ? { ...it, action: newAction } : it))
    )
    updateItem({ ...item, action: newAction })
  }

  const priorityLabel = (p: number) => {
    if (p >= 20) return t('common.priority_high')
    if (p >= 10) return t('common.priority_normal')
    return t('common.priority_low')
  }

  const priorityVariant = (p: number): 'default' | 'secondary' | 'outline' => {
    if (p >= 20) return 'default'
    if (p >= 10) return 'secondary'
    return 'outline'
  }

  return (
    <div className="flex flex-col gap-6 max-w-5xl">
      <PageHeader
        title={t('policy.title')}
        subtitle={t('policy.subtitle')}
        actions={
          <Button
            variant="ghost"
            size="icon"
            onClick={() => queryClient.invalidateQueries({ queryKey: ['notification-policy'] })}
            disabled={isFetching}
            aria-label={t('common.refresh')}
          >
            <RefreshCw className={`h-4 w-4 ${isFetching ? 'animate-spin' : ''}`} />
          </Button>
        }
      />

      {/* Table */}
      <div className="overflow-x-auto">
        {isFetching && items.length === 0 ? (
          <div className="flex items-center justify-center p-12 text-muted-foreground">
            <RefreshCw className="h-5 w-5 animate-spin mr-2" />
            {t('dashboard.loading')}
          </div>
        ) : (
          <table className="w-full text-sm border-collapse">
            <thead>
              <tr className="border-b">
                <th className="text-left px-4 py-3 font-medium text-muted-foreground w-44">
                  {t('policy.mail_type')}
                </th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground w-24">
                  {t('policy.priority')}
                </th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground">
                  {t('policy.channels')}
                </th>
                <th className="text-left px-4 py-3 font-medium text-muted-foreground w-44">
                  {t('policy.action')}
                </th>
              </tr>
            </thead>
            <tbody>
              {items.map((item) => (
                <tr
                  key={item.key}
                  className={`border-b last:border-0 transition-opacity ${
                    item.action === 'ignore' || item.action === 'silent' ? 'opacity-50' : ''
                  }`}
                >
                  {/* Mail type */}
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <TypeIcon mailKey={item.key} />
                      <span className="font-medium">{item.name}</span>
                      {item.is_system && (
                        <Badge variant="secondary" className="text-xs px-1.5 py-0">
                          System
                        </Badge>
                      )}
                    </div>
                  </td>

                  {/* Priority */}
                  <td className="px-4 py-3">
                    <Badge variant={priorityVariant(item.priority)} className="text-xs">
                      {priorityLabel(item.priority)}
                    </Badge>
                  </td>

                  {/* Channels checkboxes */}
                  <td className="px-4 py-3">
                    {item.action === 'notify' ? (
                      <div className="flex flex-wrap gap-3">
                        {item.channels.length === 0 ? (
                          <span className="text-muted-foreground text-xs">
                            {t('policy.no_channels')}
                          </span>
                        ) : (
                          item.channels.map((ch) => (
                            <label
                              key={ch.id}
                              className="flex items-center gap-1.5 cursor-pointer select-none"
                            >
                              <Checkbox
                                checked={ch.selected}
                                onCheckedChange={() => handleToggleChannel(item, ch.id)}
                                disabled={saving === item.key}
                              />
                              <span className="text-sm">{ch.name}</span>
                            </label>
                          ))
                        )}
                      </div>
                    ) : (
                      <span className="text-muted-foreground text-xs">—</span>
                    )}
                  </td>

                  {/* Action select */}
                  <td className="px-4 py-3">
                    <div className="flex items-center gap-2">
                      <Select
                        value={item.action}
                        onValueChange={(v) => handleActionChange(item, v)}
                        disabled={saving === item.key}
                      >
                        <SelectTrigger className="w-32 h-8">
                          <SelectValue />
                        </SelectTrigger>
                        <SelectContent>
                          <SelectItem value="notify">{t('policy.action_notify')}</SelectItem>
                          <SelectItem value="silent">{t('policy.action_silent')}</SelectItem>
                          <SelectItem value="ignore">{t('policy.action_ignore')}</SelectItem>
                        </SelectContent>
                      </Select>
                      {saving === item.key && (
                        <RefreshCw className="h-3.5 w-3.5 animate-spin text-muted-foreground" />
                      )}
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </div>
    </div>
  )
}

// mail2im/frontend/src/views/NotificationPolicy.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import api from '../services/api';
import PageHeader from '../components/PageHeader.vue';
import Button from 'primevue/button';
import Checkbox from 'primevue/checkbox';
import Select from 'primevue/select';
import Tag from 'primevue/tag';

const { t } = useI18n();
const toast = useToast();

interface PolicyChannel {
  id: number;
  name: string;
  type: string;
  selected: boolean;
}

interface PolicyItem {
  ID: number;
  key: string;
  name: string;
  priority: number;
  is_system: boolean;
  action: string;
  channel_ids: string;
  channels: PolicyChannel[];
}

const items = ref<PolicyItem[]>([]);
const loading = ref(false);
const saving = ref<string | null>(null);

const actionOptions = [
  { label: () => t('policy.action_notify'), value: 'notify' },
  { label: () => t('policy.action_silent'), value: 'silent' },
  { label: () => t('policy.action_ignore'), value: 'ignore' },
];

const fetchPolicy = async () => {
  loading.value = true;
  try {
    const res = await api.get('/notification-policy');
    items.value = res.data;
  } catch {
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('policy.load_error'), life: 3000 });
  } finally {
    loading.value = false;
  }
};

const updatePolicy = async (item: PolicyItem) => {
  saving.value = item.key;
  try {
    // Build channel_ids from selected channels
    const selectedIds = item.channels.filter(c => c.selected).map(c => c.id);
    await api.put(`/notification-policy/${item.key}`, {
      channel_ids: JSON.stringify(selectedIds),
      action: item.action,
      priority: item.priority,
    });
    toast.add({ severity: 'success', summary: t('common.success'), detail: t('policy.update_success'), life: 2000 });
  } catch {
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('policy.update_error'), life: 3000 });
  } finally {
    saving.value = null;
  }
};

const toggleChannel = (item: PolicyItem, channel: PolicyChannel) => {
  channel.selected = !channel.selected;
  updatePolicy(item);
};

const changeAction = (item: PolicyItem, newAction: string) => {
  item.action = newAction;
  updatePolicy(item);
};

const typeIcon = (key: string) => {
  const icons: Record<string, string> = {
    primary: 'pi pi-inbox',
    bill: 'pi pi-wallet',
    important: 'pi pi-star',
    notification: 'pi pi-bell',
    unknown: 'pi pi-question-circle',
    promotion: 'pi pi-megaphone',
    social: 'pi pi-users',
    spam: 'pi pi-ban',
    trash: 'pi pi-trash',
    draft: 'pi pi-file-edit',
    sent: 'pi pi-send',
  };
  return icons[key] || 'pi pi-tag';
};

const priorityLabel = (p: number) => {
  if (p >= 20) return t('common.priority_high');
  if (p >= 10) return t('common.priority_normal');
  return t('common.priority_low');
};

onMounted(fetchPolicy);
</script>

<template>
  <div class="page table-page">
    <PageHeader :title="t('policy.title')" :subtitle="t('policy.subtitle')">
      <template #actions>
        <Button :aria-label="t('common.refresh')" icon="pi pi-refresh" rounded text :loading="loading" @click="fetchPolicy" v-tooltip.bottom="t('common.refresh')" />
      </template>
    </PageHeader>

    <div class="page-panel policy-panel">
      <div v-if="loading" class="flex items-center justify-center p-8">
        <i class="pi pi-spin pi-spinner text-2xl" />
      </div>

      <table v-else class="policy-table">
        <thead>
          <tr>
            <th class="col-type">{{ t('policy.mail_type') }}</th>
            <th class="col-priority">{{ t('policy.priority') }}</th>
            <th class="col-channels">{{ t('policy.channels') }}</th>
            <th class="col-action">{{ t('policy.action') }}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="item in items" :key="item.key" :class="{ 'row-muted': item.action === 'ignore' || item.action === 'silent' }">
            <td class="col-type">
              <div class="flex items-center gap-2">
                <i :class="typeIcon(item.key)" />
                <span class="font-medium">{{ item.name }}</span>
                <Tag v-if="item.is_system" value="System" severity="secondary" class="text-xs" />
              </div>
            </td>
            <td class="col-priority">
              <span class="text-sm">{{ priorityLabel(item.priority) }}</span>
            </td>
            <td class="col-channels">
              <div v-if="item.action === 'notify'" class="flex flex-wrap gap-2">
                <div
                  v-for="ch in item.channels"
                  :key="ch.id"
                  class="channel-check flex items-center gap-1"
                >
                  <Checkbox
                    :modelValue="ch.selected"
                    :binary="true"
                    @update:modelValue="toggleChannel(item, ch)"
                  />
                  <span class="text-sm">{{ ch.name }}</span>
                </div>
                <span v-if="item.channels.length === 0" class="text-sm text-surface-400">{{ t('policy.no_channels') }}</span>
              </div>
              <span v-else class="text-sm text-surface-400">--</span>
            </td>
            <td class="col-action">
              <Select
                :modelValue="item.action"
                :options="actionOptions"
                :optionLabel="(o: any) => o.label()"
                optionValue="value"
                class="action-select"
                @update:modelValue="(v: string) => changeAction(item, v)"
              />
              <i v-if="saving === item.key" class="pi pi-spin pi-spinner ml-2 text-sm" />
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.policy-panel {
  overflow-x: auto;
}

.policy-table {
  width: 100%;
  border-collapse: collapse;
}

.policy-table th {
  text-align: left;
  padding: 0.75rem 1rem;
  font-weight: 600;
  font-size: 0.875rem;
  color: var(--p-text-muted-color);
  border-bottom: 2px solid var(--p-surface-200);
}

.policy-table td {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--p-surface-100);
  vertical-align: middle;
}

.row-muted {
  opacity: 0.6;
}

.col-type {
  min-width: 180px;
}

.col-priority {
  width: 100px;
}

.col-channels {
  min-width: 250px;
}

.col-action {
  width: 160px;
}

.action-select {
  width: 130px;
}

.channel-check {
  cursor: pointer;
}

:deep(.app-dark) .policy-table th {
  border-bottom-color: var(--p-surface-600);
}

:deep(.app-dark) .policy-table td {
  border-bottom-color: var(--p-surface-700);
}
</style>
