// mail2im/frontend-react/src/pages/Templates.tsx
import { useState, useEffect, useRef, useCallback } from 'react'
import { useTranslation } from 'react-i18next'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { toast } from 'sonner'
import { Plus, RefreshCw, Pencil, Trash2, TriangleAlert, FileText, Loader2 } from 'lucide-react'

import http, { extractList } from '@/services/api'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Badge } from '@/components/ui/badge'
import { PageHeader } from '@/components/PageHeader'
import { Textarea } from '@/components/ui/textarea'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogFooter,
} from '@/components/ui/dialog'
import {
  AlertDialog,
  AlertDialogContent,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogCancel,
  AlertDialogAction,
} from '@/components/ui/alert-dialog'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'

// ─── Types ────────────────────────────────────────────────────────────────────

interface Template {
  id?: number
  name: string
  content: string
  channel_type: string
  is_default: boolean
  description: string
}

interface TemplateVar {
  name: string
  description: string
  example: string
}

interface TemplateForm {
  id: number | null
  name: string
  content: string
  channel_type: string
  is_default: boolean
  description: string
}

// ─── Constants ─────────────────────────────────────────────────────────────────

const CHANNEL_TYPES = [
  { label: 'All', value: 'all' },
  { label: 'Telegram', value: 'telegram' },
  { label: 'Discord', value: 'discord' },
]

const DEFAULT_FORM: TemplateForm = {
  id: null,
  name: '',
  content: '',
  channel_type: 'all',
  is_default: false,
  description: '',
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function getChannelLabel(type: string): string {
  return CHANNEL_TYPES.find((c) => c.value === type)?.label ?? type
}

function getChannelVariant(type: string): 'default' | 'secondary' | 'destructive' | 'outline' {
  switch (type) {
    case 'telegram':
      return 'default'
    case 'discord':
      return 'secondary'
    default:
      return 'outline'
  }
}

// ─── TemplateEditorDialog ─────────────────────────────────────────────────────

interface TemplateEditorDialogProps {
  open: boolean
  onClose: () => void
  isEdit: boolean
  form: TemplateForm
  setForm: React.Dispatch<React.SetStateAction<TemplateForm>>
  variables: TemplateVar[]
  defaultTemplates: Template[]
  onSave: () => void
  isSaving: boolean
}

function TemplateEditorDialog({
  open,
  onClose,
  isEdit,
  form,
  setForm,
  variables,
  defaultTemplates,
  onSave,
  isSaving,
}: TemplateEditorDialogProps) {
  const { t } = useTranslation()
  const textareaRef = useRef<HTMLTextAreaElement>(null)
  const [preview, setPreview] = useState('')
  const [previewLoading, setPreviewLoading] = useState(false)
  const previewTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null)

  const fetchPreview = useCallback(async (content: string, channelType: string) => {
    if (!content) {
      setPreview('')
      return
    }
    setPreviewLoading(true)
    try {
      const res = await http.post('/templates/preview', { content, channel_type: channelType })
      setPreview(res.data?.preview ?? '')
    } catch {
      setPreview(t('templates.preview_error'))
    } finally {
      setPreviewLoading(false)
    }
  }, [t])

  const debouncedPreview = useCallback(
    (content: string, channelType: string) => {
      if (previewTimerRef.current) clearTimeout(previewTimerRef.current)
      previewTimerRef.current = setTimeout(() => {
        fetchPreview(content, channelType)
      }, 500)
    },
    [fetchPreview],
  )

  // Trigger preview whenever content or channel_type changes
  useEffect(() => {
    if (open) {
      debouncedPreview(form.content, form.channel_type)
    }
    return () => {
      if (previewTimerRef.current) clearTimeout(previewTimerRef.current)
    }
  }, [form.content, form.channel_type, open, debouncedPreview])

  // Reset preview when dialog opens/closes
  useEffect(() => {
    if (!open) setPreview('')
  }, [open])

  const insertVariable = (varName: string) => {
    const textarea = textareaRef.current
    const insertion = `{{.${varName}}}`
    if (textarea) {
      const start = textarea.selectionStart
      const end = textarea.selectionEnd
      const value = form.content
      const newContent = value.substring(0, start) + insertion + value.substring(end)
      setForm((f) => ({ ...f, content: newContent }))
      setTimeout(() => {
        textarea.focus()
        textarea.selectionStart = textarea.selectionEnd = start + insertion.length
      }, 0)
    } else {
      setForm((f) => ({ ...f, content: f.content + insertion }))
    }
  }

  const loadDefaultTemplate = () => {
    const match =
      defaultTemplates.find((dt) => dt.channel_type === form.channel_type) ??
      defaultTemplates.find((dt) => dt.channel_type === 'all')
    if (match) {
      setForm((f) => ({ ...f, content: match.content }))
    } else {
      toast.warning('未找到对应默认模板')
    }
  }

  return (
    <Dialog open={open} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-w-4xl max-h-[90vh] overflow-hidden flex flex-col">
        <DialogHeader>
          <DialogTitle>
            {isEdit ? t('templates.edit') : t('templates.add')}
          </DialogTitle>
        </DialogHeader>

        {/* Top row: name, channel type, description */}
        <div className="flex gap-3 flex-wrap">
          <div className="flex-1 min-w-40 space-y-1">
            <Label className="text-sm text-muted-foreground">{t('templates.name')}</Label>
            <Input
              value={form.name}
              onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))}
              placeholder="模板名称"
            />
          </div>
          <div className="w-40 space-y-1">
            <Label className="text-sm text-muted-foreground">{t('templates.channel_type')}</Label>
            <Select
              value={form.channel_type}
              onValueChange={(v) => setForm((f) => ({ ...f, channel_type: v }))}
            >
              <SelectTrigger className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                {CHANNEL_TYPES.map((c) => (
                  <SelectItem key={c.value} value={c.value}>
                    {c.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="flex-1 min-w-40 space-y-1">
            <Label className="text-sm text-muted-foreground">{t('templates.description')}</Label>
            <Input
              value={form.description}
              onChange={(e) => setForm((f) => ({ ...f, description: e.target.value }))}
              placeholder={t('templates.description_hint')}
            />
          </div>
        </div>

        {/* Split pane: editor + preview */}
        <div className="flex gap-4 flex-1 overflow-hidden min-h-0">
          {/* Left: editor */}
          <div className="flex-1 flex flex-col overflow-hidden">
            <div className="flex items-center justify-between mb-2">
              <Label className="text-sm font-medium">{t('templates.content')}</Label>
              <Button
                type="button"
                variant="ghost"
                size="sm"
                onClick={loadDefaultTemplate}
                className="h-7 text-xs"
              >
                <FileText className="h-3.5 w-3.5 mr-1" />
                {t('templates.load_default')}
              </Button>
            </div>
            <Textarea
              ref={textareaRef}
              value={form.content}
              onChange={(e) => setForm((f) => ({ ...f, content: e.target.value }))}
              placeholder={t('templates.content_placeholder')}
              className="flex-1 resize-none font-mono text-sm min-h-0"
              style={{ height: '100%' }}
            />
            {/* Variable tags */}
            {variables.length > 0 && (
              <div className="flex flex-wrap gap-1 mt-2">
                <span className="text-xs text-muted-foreground self-center mr-1">
                  {t('templates.variables')}:
                </span>
                {variables.map((v) => (
                  <button
                    key={v.name}
                    type="button"
                    title={`${v.description} — ${v.example}`}
                    onClick={() => insertVariable(v.name)}
                    className="inline-flex items-center px-2 py-0.5 rounded text-xs bg-muted hover:bg-muted/80 text-muted-foreground hover:text-foreground transition-colors font-mono"
                  >
                    {v.name}
                  </button>
                ))}
              </div>
            )}
          </div>

          {/* Right: preview */}
          <div className="flex-1 flex flex-col overflow-hidden">
            <div className="flex items-center justify-between mb-2">
              <Label className="text-sm font-medium">{t('templates.preview')}</Label>
              {previewLoading && <Loader2 className="h-3.5 w-3.5 animate-spin text-muted-foreground" />}
            </div>
            <div className="flex-1 rounded-lg border bg-muted/30 p-3 overflow-auto min-h-0">
              <pre className="text-sm whitespace-pre-wrap break-words font-sans leading-relaxed m-0 text-foreground">
                {preview || (
                  <span className="text-muted-foreground">{t('templates.preview_empty')}</span>
                )}
              </pre>
            </div>
          </div>
        </div>

        <DialogFooter className="border-t pt-4 mt-2 shrink-0">
          <Button variant="outline" onClick={onClose}>
            {t('common.cancel')}
          </Button>
          <Button onClick={onSave} disabled={isSaving}>
            {isSaving ? '保存中...' : t('common.save')}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

// ─── TemplatesPage ────────────────────────────────────────────────────────────

export function TemplatesPage() {
  const { t } = useTranslation()
  const queryClient = useQueryClient()

  const [dialogOpen, setDialogOpen] = useState(false)
  const [isEdit, setIsEdit] = useState(false)
  const [form, setForm] = useState<TemplateForm>(DEFAULT_FORM)
  const [isSaving, setIsSaving] = useState(false)
  const [deleteTarget, setDeleteTarget] = useState<Template | null>(null)

  // ── Queries ──
  const { data: templates = [], isLoading, refetch } = useQuery<Template[]>({
    queryKey: ['templates'],
    queryFn: async () => {
      const res = await http.get('/templates')
      return extractList(res.data)
    },
  })

  const { data: variables = [] } = useQuery<TemplateVar[]>({
    queryKey: ['templates-variables'],
    queryFn: async () => {
      const res = await http.get('/templates/variables')
      return extractList(res.data)
    },
  })

  const { data: defaultTemplates = [] } = useQuery<Template[]>({
    queryKey: ['templates-defaults'],
    queryFn: async () => {
      const res = await http.get('/templates/defaults')
      return extractList(res.data)
    },
  })

  // ── Delete mutation ──
  const deleteMutation = useMutation({
    mutationFn: async (id: number) => {
      await http.delete(`/templates/${id}`)
    },
    onSuccess: () => {
      toast.success(t('templates.delete_success'))
      setDeleteTarget(null)
      queryClient.invalidateQueries({ queryKey: ['templates'] })
    },
    onError: () => {
      toast.error(t('templates.delete_error'))
    },
  })

  // ── Handlers ──
  const openCreate = () => {
    setForm({ ...DEFAULT_FORM })
    setIsEdit(false)
    setDialogOpen(true)
  }

  const openEdit = (tmpl: Template) => {
    setForm({
      id: tmpl.id ?? null,
      name: tmpl.name,
      content: tmpl.content,
      channel_type: tmpl.channel_type,
      is_default: tmpl.is_default,
      description: tmpl.description,
    })
    setIsEdit(true)
    setDialogOpen(true)
  }

  const handleSave = async () => {
    if (!form.name || !form.content) {
      toast.warning('请填写模板名称和内容')
      return
    }
    setIsSaving(true)
    try {
      if (isEdit && form.id) {
        await http.put(`/templates/${form.id}`, form)
        toast.success(t('templates.update_success'))
      } else {
        await http.post('/templates', form)
        toast.success(t('templates.create_success'))
      }
      setDialogOpen(false)
      queryClient.invalidateQueries({ queryKey: ['templates'] })
    } catch (err: unknown) {
      const error = err as { response?: { data?: { error?: string } } }
      toast.error(error.response?.data?.error || t('templates.save_error'))
    } finally {
      setIsSaving(false)
    }
  }

  // ─── Render ───────────────────────────────────────────────────────────────

  return (
    <div className="flex flex-col h-full">
      {/* Page header */}
      <PageHeader
        title={t('templates.title')}
        subtitle="管理消息推送模板，支持变量替换与实时预览"
        className="px-6 py-4 border-b"
        actions={
          <>
            <Button
              variant="outline"
              size="sm"
              onClick={() => refetch()}
              disabled={isLoading}
            >
              <RefreshCw className={`h-4 w-4 ${isLoading ? 'animate-spin' : ''}`} />
            </Button>
            <Button size="sm" onClick={openCreate}>
              <Plus className="h-4 w-4 mr-1.5" />
              {t('templates.add')}
            </Button>
          </>
        }
      />

      {/* Table */}
      <div className="flex-1 overflow-auto px-6 py-4">
        <Table>
          <TableHeader>
            <TableRow>
                <TableHead>{t('templates.name')}</TableHead>
                <TableHead className="w-32">{t('templates.channel_type')}</TableHead>
                <TableHead>{t('templates.description')}</TableHead>
                <TableHead>{t('templates.content')}</TableHead>
                <TableHead className="w-24 text-right">操作</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {isLoading ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-10 text-muted-foreground text-sm">
                    加载中...
                  </TableCell>
                </TableRow>
              ) : templates.length === 0 ? (
                <TableRow>
                  <TableCell colSpan={5} className="text-center py-10 text-muted-foreground text-sm">
                    暂无模板，点击右上角新建模板
                  </TableCell>
                </TableRow>
              ) : (
                templates.map((tmpl, idx) => (
                  <TableRow key={tmpl.id ?? idx}>
                    <TableCell className="font-medium">{tmpl.name}</TableCell>
                    <TableCell>
                      <Badge variant={getChannelVariant(tmpl.channel_type)}>
                        {getChannelLabel(tmpl.channel_type)}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-sm text-muted-foreground max-w-48 truncate">
                      {tmpl.description || '-'}
                    </TableCell>
                    <TableCell className="text-xs text-muted-foreground max-w-64 truncate font-mono">
                      {tmpl.content}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex items-center justify-end gap-1">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => openEdit(tmpl)}
                        >
                          <Pencil className="h-4 w-4" />
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          className="text-destructive hover:text-destructive"
                          onClick={() => setDeleteTarget(tmpl)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </div>

      {/* Template Editor Dialog */}
      <TemplateEditorDialog
        open={dialogOpen}
        onClose={() => setDialogOpen(false)}
        isEdit={isEdit}
        form={form}
        setForm={setForm}
        variables={variables}
        defaultTemplates={defaultTemplates}
        onSave={handleSave}
        isSaving={isSaving}
      />

      {/* Delete Confirm */}
      <AlertDialog
        open={deleteTarget !== null}
        onOpenChange={(open) => { if (!open) setDeleteTarget(null) }}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <div className="mx-auto mb-2 flex size-12 items-center justify-center rounded-full bg-destructive/10">
              <TriangleAlert className="h-6 w-6 text-destructive" />
            </div>
            <AlertDialogTitle>{t('common.confirm')}</AlertDialogTitle>
            <AlertDialogDescription>
              确定要删除模板
              {deleteTarget && (
                <span className="font-medium text-foreground"> {deleteTarget.name}</span>
              )}
              吗？此操作无法撤销。
            </AlertDialogDescription>
          </AlertDialogHeader>
          <AlertDialogFooter>
            <AlertDialogCancel>{t('common.cancel')}</AlertDialogCancel>
            <AlertDialogAction
              className="bg-destructive text-white hover:bg-destructive/90"
              onClick={() => deleteTarget?.id !== undefined && deleteMutation.mutate(deleteTarget.id)}
              disabled={deleteMutation.isPending}
            >
              {t('common.yes')}
            </AlertDialogAction>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

// mail2im/frontend/src/views/Templates.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue';
import { useI18n } from 'vue-i18n';
import { useToast } from 'primevue/usetoast';
import api from '../services/api';
import PageHeader from '../components/PageHeader.vue';
import DataTable from 'primevue/datatable';
import Column from 'primevue/column';
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Dialog from 'primevue/dialog';
import Select from 'primevue/select';
import Tag from 'primevue/tag';

const { t } = useI18n();
const toast = useToast();

interface TemplateVar {
  name: string;
  description: string;
  example: string;
}

interface Template {
  id?: number;
  name: string;
  content: string;
  channel_type: string;
  is_default: boolean;
  description: string;
}

const templates = ref<Template[]>([]);
const loading = ref(false);
const templateDialog = ref(false);
const templateForm = ref<Template>({ name: '', content: '', channel_type: 'all', is_default: false, description: '' });
const isEditTemplate = ref(false);

const variables = ref<TemplateVar[]>([]);
const preview = ref('');
const previewLoading = ref(false);
let previewTimer: ReturnType<typeof setTimeout> | null = null;

const channelTypeOptions = [
  { label: 'All', value: 'all' },
  { label: 'Telegram', value: 'telegram' },
  { label: 'Discord', value: 'discord' },
];

const defaultTemplates = ref<Template[]>([]);

const fetchTemplates = async () => {
  loading.value = true;
  try {
    const res = await api.get('/templates');
    templates.value = res.data;
  } catch {
    toast.add({ severity: 'error', summary: t('common.error'), detail: t('templates.load_error'), life: 3000 });
  } finally {
    loading.value = false;
  }
};

const fetchVariables = async () => {
  try {
    const res = await api.get('/templates/variables');
    variables.value = res.data;
  } catch {
    // non-critical
  }
};

const fetchDefaultTemplates = async () => {
  try {
    const res = await api.get('/templates/defaults');
    defaultTemplates.value = res.data;
  } catch {
    // non-critical
  }
};

const fetchPreview = async () => {
  if (!templateForm.value.content) {
    preview.value = '';
    return;
  }
  previewLoading.value = true;
  try {
    const res = await api.post('/templates/preview', {
      content: templateForm.value.content,
      channel_type: templateForm.value.channel_type,
    });
    preview.value = res.data.preview;
  } catch {
    preview.value = t('templates.preview_error');
  } finally {
    previewLoading.value = false;
  }
};

const debouncedPreview = () => {
  if (previewTimer) clearTimeout(previewTimer);
  previewTimer = setTimeout(fetchPreview, 500);
};

watch(() => templateForm.value.content, debouncedPreview);
watch(() => templateForm.value.channel_type, debouncedPreview);

const openCreateTemplate = () => {
  templateForm.value = { name: '', content: '', channel_type: 'all', is_default: false, description: '' };
  isEditTemplate.value = false;
  preview.value = '';
  templateDialog.value = true;
};

const openEditTemplate = (tmpl: Template) => {
  templateForm.value = { ...tmpl };
  isEditTemplate.value = true;
  preview.value = '';
  templateDialog.value = true;
  // Trigger preview
  debouncedPreview();
};

const saveTemplate = async () => {
  try {
    if (isEditTemplate.value && templateForm.value.id) {
      await api.put(`/templates/${templateForm.value.id}`, templateForm.value);
      toast.add({ severity: 'success', summary: t('common.success'), detail: t('templates.update_success'), life: 3000 });
    } else {
      await api.post('/templates', templateForm.value);
      toast.add({ severity: 'success', summary: t('common.success'), detail: t('templates.create_success'), life: 3000 });
    }
    templateDialog.value = false;
    fetchTemplates();
  } catch (error: any) {
    toast.add({ severity: 'error', summary: t('common.error'), detail: error.response?.data?.error || t('templates.save_error'), life: 3000 });
  }
};

const deleteTemplate = async (tmpl: Template) => {
  if (!confirm(t('common.delete_confirm', { name: tmpl.name }))) return;
  try {
    await api.delete(`/templates/${tmpl.id}`);
    toast.add({ severity: 'success', summary: t('common.success'), detail: t('templates.delete_success'), life: 3000 });
    fetchTemplates();
  } catch (error: any) {
    toast.add({ severity: 'error', summary: t('common.error'), detail: error.response?.data?.error || t('templates.delete_error'), life: 3000 });
  }
};

const insertVariable = (varName: string) => {
  const textarea = document.getElementById('templateContent') as HTMLTextAreaElement | null;
  const insertion = `{{.${varName}}}`;
  if (textarea) {
    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const value = templateForm.value.content;
    templateForm.value.content = value.substring(0, start) + insertion + value.substring(end);
    // Restore cursor position after insertion
    setTimeout(() => {
      textarea.focus();
      textarea.selectionStart = textarea.selectionEnd = start + insertion.length;
    }, 0);
  } else {
    templateForm.value.content += insertion;
  }
};

const loadDefaultTemplate = () => {
  const channelType = templateForm.value.channel_type;
  const match = defaultTemplates.value.find(
    t => t.channel_type === channelType
  ) || defaultTemplates.value.find(
    t => t.channel_type === 'all'
  );
  if (match) {
    templateForm.value.content = match.content;
  }
};

const channelTypeLabel = (type: string) => {
  const opt = channelTypeOptions.find(o => o.value === type);
  return opt ? opt.label : type;
};

const channelTypeSeverity = (type: string): "secondary" | "info" | "success" | "warn" | "danger" | "contrast" | undefined => {
  switch (type) {
    case 'telegram': return 'info';
    case 'discord': return 'success';
    default: return 'secondary';
  }
};

onMounted(() => {
  fetchTemplates();
  fetchVariables();
  fetchDefaultTemplates();
});
</script>

<template>
  <div class="page table-page">
    <PageHeader :title="t('templates.title')">
      <template #actions>
        <Button :label="t('templates.add')" icon="pi pi-plus" class="mr-2" @click="openCreateTemplate" />
        <Button :aria-label="t('common.refresh')" icon="pi pi-refresh" rounded text :loading="loading" @click="fetchTemplates" v-tooltip.bottom="t('common.refresh')" />
      </template>
    </PageHeader>

    <div class="page-panel table-panel">
      <DataTable
        :value="templates"
        :loading="loading"
        stripedRows
        scrollable
        scrollHeight="flex"
        class="table-fill"
      >
        <Column field="name" :header="t('templates.name')"></Column>
        <Column field="channel_type" :header="t('templates.channel_type')" style="width: 120px">
          <template #body="slotProps">
            <Tag :value="channelTypeLabel(slotProps.data.channel_type)" :severity="channelTypeSeverity(slotProps.data.channel_type)" />
          </template>
        </Column>
        <Column field="description" :header="t('templates.description')">
          <template #body="slotProps">
            <span class="text-sm text-surface-500">{{ slotProps.data.description }}</span>
          </template>
        </Column>
        <Column field="content" :header="t('templates.content')">
          <template #body="slotProps">
            <span class="text-xs text-surface-500 line-clamp-2">{{ slotProps.data.content }}</span>
          </template>
        </Column>
        <Column :exportable="false" style="min-width: 10rem">
          <template #body="slotProps">
            <Button icon="pi pi-pencil" outlined rounded class="mr-2" @click="openEditTemplate(slotProps.data)" />
            <Button icon="pi pi-trash" outlined rounded severity="danger" @click="deleteTemplate(slotProps.data)" />
          </template>
        </Column>
      </DataTable>
    </div>

    <!-- Template Editor Dialog -->
    <Dialog v-model:visible="templateDialog" :style="{ width: '1000px', maxWidth: '95vw' }" :header="isEditTemplate ? t('templates.edit') : t('templates.add')" :modal="true" class="p-fluid">
      <!-- Top row: name, channel type, description -->
      <div class="flex gap-4 mb-4">
        <div class="field flex-1">
          <label for="templateName">{{ t('templates.name') }}</label>
          <InputText id="templateName" v-model="templateForm.name" required class="w-full" />
        </div>
        <div class="field" style="width: 160px">
          <label for="templateChannelType">{{ t('templates.channel_type') }}</label>
          <Select id="templateChannelType" v-model="templateForm.channel_type" :options="channelTypeOptions" optionLabel="label" optionValue="value" class="w-full" />
        </div>
      </div>
      <div class="field mb-4">
        <label for="templateDesc">{{ t('templates.description') }}</label>
        <InputText id="templateDesc" v-model="templateForm.description" class="w-full" :placeholder="t('templates.description_hint')" />
      </div>

      <!-- Split pane: editor + preview -->
      <div class="editor-split">
        <div class="editor-left">
          <div class="flex items-center justify-between mb-2">
            <label class="font-medium">{{ t('templates.content') }}</label>
            <Button :label="t('templates.load_default')" icon="pi pi-file" text size="small" @click="loadDefaultTemplate" />
          </div>
          <Textarea id="templateContent" v-model="templateForm.content" rows="14" class="w-full font-mono text-sm" :placeholder="t('templates.content_placeholder')" />

          <!-- Variable tags -->
          <div class="var-tags mt-2">
            <span class="text-sm text-surface-500 mr-2">{{ t('templates.variables') }}:</span>
            <Button
              v-for="v in variables"
              :key="v.name"
              :label="v.name"
              size="small"
              text
              severity="secondary"
              class="var-tag"
              @click="insertVariable(v.name)"
              v-tooltip.top="v.description + ' — ' + v.example"
            />
          </div>
        </div>

        <div class="editor-right">
          <div class="flex items-center justify-between mb-2">
            <label class="font-medium">{{ t('templates.preview') }}</label>
            <i v-if="previewLoading" class="pi pi-spin pi-spinner text-surface-400" />
          </div>
          <div class="preview-box">
            <pre class="preview-content">{{ preview || t('templates.preview_empty') }}</pre>
          </div>
        </div>
      </div>

      <template #footer>
        <Button :label="t('common.cancel')" icon="pi pi-times" outlined @click="templateDialog = false" />
        <Button :label="t('common.save')" icon="pi pi-check" @click="saveTemplate" />
      </template>
    </Dialog>
  </div>
</template>

<style scoped>
.table-fill {
  min-height: 400px;
}

.field label {
  display: block;
  margin-bottom: 0.5rem;
  font-weight: 500;
  color: var(--text-color);
}

.editor-split {
  display: flex;
  gap: 1rem;
  min-height: 400px;
}

.editor-left {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.editor-right {
  flex: 1;
  display: flex;
  flex-direction: column;
}

.preview-box {
  flex: 1;
  border: 1px solid var(--p-surface-300);
  border-radius: var(--p-border-radius);
  padding: 0.75rem;
  background: var(--p-surface-50);
  overflow: auto;
  min-height: 320px;
}

:deep(.app-dark) .preview-box,
.app-dark .preview-box {
  background: var(--p-surface-800);
  border-color: var(--p-surface-600);
}

.preview-content {
  margin: 0;
  white-space: pre-wrap;
  word-break: break-word;
  font-family: inherit;
  font-size: 0.875rem;
  line-height: 1.5;
  color: var(--text-color);
}

.var-tags {
  display: flex;
  flex-wrap: wrap;
  align-items: center;
  gap: 0.25rem;
}

.var-tag {
  font-size: 0.75rem !important;
  padding: 0.15rem 0.5rem !important;
}

.font-mono {
  font-family: 'JetBrains Mono', 'Fira Code', 'Consolas', monospace;
}

@media (max-width: 768px) {
  .editor-split {
    flex-direction: column;
  }
}
</style>
